CourWork2024/Controllers/ImagesController.cs
using CourWork2024.Data;
using CourWork2024.Models;
using Microsoft.AspNetCore.Mvc;

namespace CourWork2024.Controllers
{
    public class ImagesController : Controller
    {
        private readonly CourWork2024Context _context;

        public ImagesController(CourWork2024Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            var imagesPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images");
            if (!Directory.Exists(imagesPath))
            {
                Directory.CreateDirectory(imagesPath);
            }
            var picture = new Picture { ImagePath = file.FileName };
            _context.Pictures.Add(picture);
            await _context.SaveChangesAsync();
            var filePath = Path.Combine(imagesPath, Path.GetFileName(file.FileName));
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            return View();
        }
    }
}

CourWork2024/Views/Images/Upload.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using (Html.BeginForm("Upload", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" value="Upload" />
}